// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMkBK1jEgPNvJMAa_EqO3a3j3QsjCdDDw',
    appId: '1:532695605835:web:171fbe70e3a21284c923ce',
    messagingSenderId: '532695605835',
    projectId: 'mad-hw5-d72f7',
    authDomain: 'mad-hw5-d72f7.firebaseapp.com',
    storageBucket: 'mad-hw5-d72f7.firebasestorage.app',
    measurementId: 'G-PS8VNBLD18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq213WTruJcd1Kxz358Sd0sulMI5DgdzE',
    appId: '1:532695605835:android:cedb1dca42b59972c923ce',
    messagingSenderId: '532695605835',
    projectId: 'mad-hw5-d72f7',
    storageBucket: 'mad-hw5-d72f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtaDX-qRqcwyHXl4mroVqos42hCtiUQLc',
    appId: '1:532695605835:ios:668e642853d233cdc923ce',
    messagingSenderId: '532695605835',
    projectId: 'mad-hw5-d72f7',
    storageBucket: 'mad-hw5-d72f7.firebasestorage.app',
    iosBundleId: 'com.example.madHw5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtaDX-qRqcwyHXl4mroVqos42hCtiUQLc',
    appId: '1:532695605835:ios:668e642853d233cdc923ce',
    messagingSenderId: '532695605835',
    projectId: 'mad-hw5-d72f7',
    storageBucket: 'mad-hw5-d72f7.firebasestorage.app',
    iosBundleId: 'com.example.madHw5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMkBK1jEgPNvJMAa_EqO3a3j3QsjCdDDw',
    appId: '1:532695605835:web:1df358c3823a7a5cc923ce',
    messagingSenderId: '532695605835',
    projectId: 'mad-hw5-d72f7',
    authDomain: 'mad-hw5-d72f7.firebaseapp.com',
    storageBucket: 'mad-hw5-d72f7.firebasestorage.app',
    measurementId: 'G-XD3QKBWJ51',
  );
}
